[package]
name = "third-principles-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
azalea = { git = "https://github.com/azalea-rs/azalea", branch = "1.21.11" }
dotenvy = "0.15.7"
eyre = "0.6.12"
parking_lot = "0.12"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = "1.51.0"
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
